# Generated by Django 6.0.3 on 2026-06-06 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_books_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('cover_url', models.URLField(blank=True)),
                ('starred_by', models.ManyToManyField(blank=True, related_name='starred_books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
