# Generated by Django 6.0.3 on 2026-06-06 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_author_book_pages_book_published_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
